### ISSUE TITLE
[ISSU] Trade

### ISSUE THREAD

**Issue by tannerflick4** [Altemio/SevenKingdoms-master#14] opened 2017-04-26 19:44 UTC
Team - I am starting to dabble in our mod's trade routes. But since these can affect the game greatly, I am going to make my trade routes file in my locker, where you can copy it into your main game if you want to, but its your decision. This is because I will be experimenting with these a lot to try to understand more where to have these routes and which provs they go through, etc.

Feel free to leave a note here about your opinion on routes and anything else about trade.

**Comment by thestonedigger** [comment] 2017-04-26 22:08
I'm looking forward to testing them out once you feel like they are less experimental!

**Comment by RowanMaBoot** [comment] 2017-04-27 16:36
There probably should be something going through the Arbor/Oldtown up to Highgarden. Not sure where the end node would be.

The free cities could all be linked up, and perhaps the trade would then be redirected from the free cities into blackwater bay, or not at all.

Maybe there should be a node from winterfell, through to the the Twins, where it forks down to Lord Harroway's Town/The Vale (or Bronze route) whilst the other fork goes Riverrun, Westerlands and probably the reach.

**Comment by tannerflick4** [comment] 2017-04-27 16:52
Yeah I was thinking of having a "main branch" and then having a secondary branch which would go through all the duchy capitals. I've made a list for the Vale, but if you think this would be too much im okay with just doing the main branch.

**Comment by tannerflick4** [comment] 2017-04-29 02:11
Ok - After a lot of trying to work with trade, I am retiring from working on it. I just think it would be better if someone else took trade duty.

**Comment by RowanMaBoot** [comment] 2017-04-29 18:03
I'll have a crack at it later.

**Comment by RowanMaBoot** [comment] 2017-05-22 07:17
If stability is confirmed to be good to go, I'll get working on this over this week.

**Comment by RowanMaBoot** [comment] 2017-10-19 17:46
Just a small update; trade routes are still bugged, and cause crashes for an unknown reason. A number of people have looked into it, and have not been able to determine the cause.

This issue will be investigated long-term, and I will get round to creating some limited trade routes of a small scope - example would be a route that goes over water, or a local route in Essos.

**Comment by blackninja9939** [comment] 2017-10-24 20:59
Your best bet is to just re-script the entire thing, there is an error somewhere so remaking it should eliminate that.

**Comment by RowanMaBoot** [comment] 2017-10-24 21:11
Entirely possible, although we've had two others make entirely new test routes and they have also experienced the crashes.

Once I get some free time (working a long ass day atm), I'll get testing and do some really simple routes and see what is what.

**Comment by TitanRogue** [comment] 2018-07-23 15:10
@Altemio 
When were the gfx files in the interface folder last updated? Since the whole trade view is bugged (when trade routes are enabled) and I figured out that some interface stuff isn't listed in any gfx file.

**Comment by RowanMaBoot** [comment] 2018-07-23 23:37
@TitanRogue 
It (the main.gui for example) hasn't been updated in four months, although crashing has been going on since the mod's conception - before any updates. Not even blackninja could work out what was wrong. 

I'll give them a glance when I'm next off, since I'm not sure if all of them were updated for JD. We're assuming the crashing is related to events.

**Comment by TitanRogue** [comment] 2018-07-24 10:04
@Altemio 
I have talked with a modder who added many trade routes to the vanilla game and also HIP and CK2+. I sent him some test routes and they worked for him. He launched from a seperate mod and deleted the replace path : trade_route from our mod's mod file and he got no crashes. I followed his instructions but the game still crashed. I will disable every JD event related to trade routes and test whether that is a solution.

**Comment by TitanRogue** [comment] 2018-08-08 15:50
@Altemio 
I don´t think the crashes are caused by events. I deleted all of them but the game still crashes. Maybe buildings cause it or missing modifiers.

Update:
I might have found whats causing the issues. I checked the common/holdingtypes/00_holding_types and deleted "silk_road_trade_post_trigger = yes" and "trade_route = silk_road". The game did not crash.
trade_post = {
	trigger = {
		conditional_tooltip = {
			trigger = {
				#trade_route = silk_road
				OR = {
					FROM = {
						is_patrician = no
					}
					AND = {
						port = no
						FROM = {
							is_patrician = yes
						}
					}
				}
			}
			#silk_road_trade_post_trigger = yes
		}
	}
}
When it looks like this the game should not crash. Unfortunately it seems to work for me only. Vierwood tried to run some custom routes himself but without any success. I don't know why it works in my game but not in others.

**Comment by RowanMaBoot** [comment] 2019-07-27 14:08
Did we ever find out exactly what was missing, and therefore caused the crashes?

**Comment by TitanRogue** [comment] 2019-07-27 14:38
I do not know but with the trade routes I added so far I have not experienced any crashes. So I guess the issue was fixed by our reconversion of vanilla files.

**Comment by RowanMaBoot** [comment] 2019-07-27 21:08
Great! Would've been good to know what caused it.

**Closed as completed by RowanMaBoot** 2019-07-27 21:08 UTC
Labels: bug, help wanted, blocker
